### ISSUE TITLE
Fatal error: Class 'Icinga\Module\Nagvis\Forms\Config\BackendConfigForm' not found

### ISSUE THREAD

**Issue by splintersnake** [divetoh/icingaweb2-module-nagvis#1]
Hi,
Thanks for your module but there is an issue when I want to configure Nagvis URL, in configuration tab on Icingaweb2 interface I get this message:

Fatal error: Class 'Icinga\Module\Nagvis\Forms\Config\BackendConfigForm' not found in /usr/share/icingaweb/modules/nagvis/application/controllers/ConfigController.php on line 10

Line 10 in ConfigController.php refers to this line:  $form = new BackendConfigForm();

I have compared with other modules like monitoring but I am not able to resolve this matter.

Thanks in advance
Mike

**Comment by divetoh** [comment]
Hello!
Have you directory: /usr/share/icingaweb/modules/nagvis/library/Nagvis ? It's empty, but you must create it for correct work.
If you allready have this directory - check access right to files and directories.

Also, you can create config "by hands". Create file /usr/share/icingaweb/config/modules/nagvis/config.ini with content:

>   [nagvis]
>   nagvis_url          = "http://you.url.here/nagvis/"

**Comment by splintersnake** [comment]
It's working, thank you for your prompt reply.
I have created the folders "library" and "nagvis" under it.

The tap appears in the interface and then I have applied apache rights on /etc/icingaweb/modules/nagvis

Many thanks
Mike
