### ISSUE TITLE
module configuration tab 

### ISSUE THREAD

**Issue by Django-BOfH** [divetoh/icingaweb2-module-nagvis#2]
I've installed this module and I've enabled the nagvis module. But there's no "module configuration tab" where I can set up the URL to my nagvis interface.
Name        : icingaweb2
Version     : 2.0.0
Release     : 3.beta3.el7.centos

Name        : icinga2
Version     : 2.3.3
Release     : 1.el7.centos

NagVis 1.8.2

**Comment by divetoh** [comment]
Hi! Mayby somthing change in last version of incingaweb2, tomorow i will try to update and fix error.

Try open direct: http://.../icingaweb2/nagvis/config

Also you can create config "by hands". Create file /path_to_incingaweb2/config/modules/nagvis/config.ini with content:

> [nagvis]
> nagvis_url = "http://you.url.here/nagvis/"

**Comment by Django-BOfH** [comment]
Pardon, there was a typo in my path! m( Everything works very well!
