### ISSUE TITLE
iframe in iframe

### ISSUE THREAD

**Issue by Django-BOfH** [divetoh/icingaweb2-module-nagvis#3]
HI,

I'm using NagVis 1.2.8, Icinga Web 2 2.0.0. I set up an automap of my testenviroment and have a strange behavior . If I click on a host of my automap a further iframe is embedded in the actual one!

![nagvis](https://cloud.githubusercontent.com/assets/6991904/7231423/80ced40c-e775-11e4-96c4-c0ee153e15ed.png)
Do you have an idea, what went wrong?

ttyl
Django

**Comment by divetoh** [comment]
Do you set "urltarget" parameter? (see https://github.com/divetoh/icingaweb2-module-nagvis/blob/master/nagvis/doc/index.md)

**Comment by Django-BOfH** [comment]
You made my day!

With urltarget="_parent" it works!

1,000 thanx
