### ISSUE TITLE
Nagvis button/tab not showing up

### ISSUE THREAD

**Issue by arioch** [divetoh/icingaweb2-module-nagvis#4]
I've cloned the repo to my module directory and enabled the module in IcingaWeb2 (system - modules - nagvis). However I don't get to see the new tab. 

Is there something I need to configure for it to show up?

![nagvis](https://cloud.githubusercontent.com/assets/289522/7344112/3de0c444-ecc9-11e4-865a-42d876f21429.png)

**Comment by divetoh** [comment]
Try to open config tab by direct link: http://.../icingaweb2/nagvis/config

Which version of icingaweb2 you using?

**Comment by arioch** [comment]
It throws a 404 on /icingaweb/nagvis/config and /icingaweb/nagvis.

icingaweb2-2.0.0-3.beta3.el7.centos

**Comment by divetoh** [comment]
I'll update my version and try to fix it soon.

You can create config "by hands". Create file /path_to_incingaweb2/config/modules/nagvis/config.ini with content:

> [nagvis]
> nagvis_url = "http://you.url.here/nagvis/"

**Comment by arioch** [comment]
Great, thanks.

In the meantime I've added support for your module to our [puppet module](https://git.icinga.org/?p=puppet-icingaweb2.git;a=commit;h=2b634be4a57189b205902dd281e578f38e433709;js=1).

**Comment by divetoh** [comment]
Looks like you copy all repository in module directory, but you need to copy only 'nagvis' directory. On you screenshot version 0.0.0 and no description, but in file 'module.info' version is 0.0.1 and description: 'Nagvis iframe.'. If you copy is correct 'module.info' will be placed in /.../icingaweb2/modules/nagvis/module.info.

**Comment by arioch** [comment]
That seems to do the trick.
It's not conform the other IcingaWeb2 modules' structure though.

**Comment by divetoh** [comment]
No problem, i'll move nagvis to root of repository. Few mintes.

**Comment by divetoh** [comment]
Moved. Try clone repo now.

**Comment by arioch** [comment]
Awesome! :+1:

Everything has been resolved, other than the lack of RHEL 7 NagVis packages but that's out of scope.
I'll go ahead and close this ticket.

Thanks again.
