### ISSUE TITLE
DataView Hostdependency does not exist

### ISSUE THREAD

**Issue by brandher** [divetoh/icingaweb2-module-nagvis#5]
I get the above error with the following trace when I open the lin to the statusmap in my Icinga Webpage

Der ist no Hostdependency.php and no HostdependencyQuery.php 
thanks in advance for your help
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(259): Icinga\Module\Monitoring\Backend\MonitoringBackend->buildViewClassName('hostdependency')
#1 /usr/share/icingaweb2/modules/statusmap/application/controllers/IndexController.php(36): Icinga\Module\Monitoring\Backend\MonitoringBackend->from('hostdependency', Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): StatusMap_IndexController->indexAction()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch('indexAction')
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(56): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}

**Comment by divetoh** [comment]
Hi. What URL you open?

**Comment by brandher** [comment]
http://192.168.100.151/icingaweb2/statusmap

**Comment by divetoh** [comment]
You use this module: icingaweb2-module-statusmap. View readme.md (https://github.com/invliD/icingaweb2-module-statusmap/blob/master/README.md) - you need make two symlink for files HostdependencyQuery.php and Hostdependency.php.

**Comment by brandher** [comment]
I know this readme.
unfortunately there is no:
/usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdependencyQuery.php
and no:
/usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/Hostdependency.php

my result is:
![capture](https://cloud.githubusercontent.com/assets/12811636/17967227/3626f062-6ac6-11e6-9d76-39e782ba9de8.PNG)

**Comment by brandher** [comment]
this is what I have there
![capture](https://cloud.githubusercontent.com/assets/12811636/17967292/a0929438-6ac6-11e6-81bd-9e94e16385bf.PNG)

**Comment by brandher** [comment]
OK I did this one, it is fine now
![capture](https://cloud.githubusercontent.com/assets/12811636/17967869/f41b5a2e-6ac9-11e6-935c-2770d299210b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12811636/17967870/f8771cca-6ac9-11e6-8c33-f1b583082aaf.PNG)
